s = set()
# n = input("Enter a number: ")
# s.add(int(n))
n=int(input("Enter a number: "))
s.add(n)
n=int(input("Enter a number: "))
s.add(n)
n=int(input("Enter a number: "))
s.add(n)
n=int(input("Enter a number: "))
s.add(n)
n=int(input("Enter a number: "))
s.add(n)
print(s)